// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDJCgBr2xR0UBnsFmGlntWhyVaqaQq98E',
    appId: '1:945693826861:web:11169c9205edc960407da4',
    messagingSenderId: '945693826861',
    projectId: 'eshop-app-5d35c',
    authDomain: 'eshop-app-5d35c.firebaseapp.com',
    storageBucket: 'eshop-app-5d35c.appspot.com',
    measurementId: 'G-FPK5JFF84Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlb1Ba8iX6e4zcPkx3SHYeWxSi4x6RL3k',
    appId: '1:945693826861:android:eacc15e947f12bac407da4',
    messagingSenderId: '945693826861',
    projectId: 'eshop-app-5d35c',
    storageBucket: 'eshop-app-5d35c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-ZxtNwkTFstwFx6-V3IDfTSnBOE1Sfk',
    appId: '1:945693826861:ios:e2d2eeda83b9a906407da4',
    messagingSenderId: '945693826861',
    projectId: 'eshop-app-5d35c',
    storageBucket: 'eshop-app-5d35c.appspot.com',
    androidClientId: '945693826861-8u0l52nfh44pc0qtnmsqfc1fmsprvg85.apps.googleusercontent.com',
    iosClientId: '945693826861-uk8gu4iggnlvli1se9lj94q3sco2c5v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_-ZxtNwkTFstwFx6-V3IDfTSnBOE1Sfk',
    appId: '1:945693826861:ios:e2d2eeda83b9a906407da4',
    messagingSenderId: '945693826861',
    projectId: 'eshop-app-5d35c',
    storageBucket: 'eshop-app-5d35c.appspot.com',
    androidClientId: '945693826861-8u0l52nfh44pc0qtnmsqfc1fmsprvg85.apps.googleusercontent.com',
    iosClientId: '945693826861-uk8gu4iggnlvli1se9lj94q3sco2c5v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDJCgBr2xR0UBnsFmGlntWhyVaqaQq98E',
    appId: '1:945693826861:web:dc915a71f8efc2c0407da4',
    messagingSenderId: '945693826861',
    projectId: 'eshop-app-5d35c',
    authDomain: 'eshop-app-5d35c.firebaseapp.com',
    storageBucket: 'eshop-app-5d35c.appspot.com',
    measurementId: 'G-7HH058XF5P',
  );

}