// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdz91Pehfgh6y5RfNEXHGe6n3Bi5oKDpk',
    appId: '1:430472490040:web:a882fb4dacd6902a2ccacd',
    messagingSenderId: '430472490040',
    projectId: 'kiotminimanager',
    authDomain: 'kiotminimanager.firebaseapp.com',
    storageBucket: 'kiotminimanager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEar9CEsOeh-yiyVSnQSUfBr0gBa3Op0M',
    appId: '1:430472490040:android:e7b229068b3204b72ccacd',
    messagingSenderId: '430472490040',
    projectId: 'kiotminimanager',
    storageBucket: 'kiotminimanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN0fqK-ks2UQFEStLPYcZVVsO_DVH-NGg',
    appId: '1:430472490040:ios:4ca55d450d0c774f2ccacd',
    messagingSenderId: '430472490040',
    projectId: 'kiotminimanager',
    storageBucket: 'kiotminimanager.appspot.com',
    androidClientId: '430472490040-vnsc3tnrbjd8u80p5p1cg1t2fnmihmat.apps.googleusercontent.com',
    iosClientId: '430472490040-enpipb2qets4ovi0f5t6kj24hm5ijac9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN0fqK-ks2UQFEStLPYcZVVsO_DVH-NGg',
    appId: '1:430472490040:ios:4ca55d450d0c774f2ccacd',
    messagingSenderId: '430472490040',
    projectId: 'kiotminimanager',
    storageBucket: 'kiotminimanager.appspot.com',
    iosBundleId: 'com.example.eStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdz91Pehfgh6y5RfNEXHGe6n3Bi5oKDpk',
    appId: '1:430472490040:web:314aecfb118a27582ccacd',
    messagingSenderId: '430472490040',
    projectId: 'kiotminimanager',
    authDomain: 'kiotminimanager.firebaseapp.com',
    storageBucket: 'kiotminimanager.appspot.com',
  );
}